#!/usr/bin/env bash
#Script to display information about subdomains

display_info ()
{
	domain="$1"
	subdoman="$2"
	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is %s record and points to %s\n}' var="$subdomain"

}

for subdomain in "www" "lib-01" "web-01" "web-02"
do
	if [ -z "$2"] || [ "$2" == "$subdomain" ] ;
	then
	display_info "$1" "$subdomain"
	fi
done
