#!/usr/bin/env bash

# This script transfers a file from client to server
# using secure copy (scp)

filename=$(basename "$BASH_SOURCE")
if [ "$#" -lt 4 ]; then
	echo -e "Usage: $filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
