#!/usr/bin/env bash

# This script transfers a file from client to server
# using secure copy (scp)

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o ScrictHostKeyChecking=no -i $4 $1 $3@$2 ~/
